Сделал сервис для работы с API
uevuu/-Kitchen-Buddy-IOS-app pull request #1
Opened 2023-04-01 22:41 UTC by uevuu

Тестировал на этапе загрузки контроллера

2023-04-05 02:58 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Services/MockNetworkService.swift
> +class MockNetworkService: NetworkServiceProtocol{
ставь отступ всегда перед открываем скобки

2023-04-05 02:59 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Services/NetworkService.swift
> +
лишние отступы

2023-04-05 03:00 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Models/CuisineType.swift
> +enum CuisineType: String, CaseIterable{
ставь отступ всегда перед открытием скобки

2023-04-05 03:01 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Services/MockNetworkService.swift
> +class MockNetworkService: NetworkServiceProtocol{
для чего тебе MockNetworkService?

2023-04-05 03:03 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Services/NetworkService.swift
> +        let encodedString = (baseURl + apiURL).addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)
здесь было бы круто заюзать Alamofire+Moya библиотеки (для сетевого слоя)

2023-04-05 03:03 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Services/NetworkService.swift
> +class NetworkService: NetworkServiceProtocol{
здесь было бы круто заюзать Alamofire+Moya библиотеки (для сетевого слоя)

2023-04-05 07:23 UTC, uevuu commented on Kitchen Buddy/Kitchen Buddy/Services/MockNetworkService.swift
> +class MockNetworkService: NetworkServiceProtocol{
Работать с ним вместо обычного, чтобы не тратить запросы к апи

2023-04-12 16:48 UTC, SviRiDoFFtru requested changes

2023-04-12 16:48 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Services/NetworkService.swift
> +    func getRecipes(
не совсем правильно понял, что мы обсуждали) конкретные запросы по теме и параметры к ним должны быть описаны в отдельных таргетах (напр. RecipesApiTarget, который наследуется от Moya.TargetType), а интерфейс NetworkServiceProtocol должен выглядеть один два универсальных метода для отправки любого запроса из твоего приложения (например вот такой:  
```swift
@discardableResult
    func sendRequest<Parser: NetworkResponseParserProtocol>(
        target: Moya.TargetType,
        parser: Parser,
        errorParser: ServerErrorParserProtocol?,
        completion: @escaping (Result<Parser.ResponseType, Error>) -> Void
    ) -> Cancellable
```
)

2023-04-12 16:48 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Services/MoyaAPIService.swift
> +            let query,
Вот тут можно кстати все параметры объединить в одну модельку ***RequestModel

2023-04-12 16:48 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Services/MoyaAPIService.swift
> +    private func complexSearchParameters(
Вроде не используется, можно удалить

2023-04-12 16:48 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Services/NetworkService.swift
> +    func createRequest<T: Decodable>(target: MoyaAPIService, completion: @escaping (Result<T, Error>) -> Void)
Правильней будет навать sendRequest

2023-04-12 16:48 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/ViewController.swift
> +        )) { (result: Result<FoundIngredients, Error>) in
Вот здесь разве не дает просто result написать? Можно просто { result in ...
Этот VC для теста, я понял, можешь не править, но потом не забудь когда переносить будешь

2023-04-12 16:48 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/ViewController.swift
> +            target: .getIngredients(
Старайся декомпозировать такие вещи
(создание таргета перенеси выше), а то тут каша из кода получается)))

2023-04-12 22:05 UTC, uevuu commented on Kitchen Buddy/Kitchen Buddy/ViewController.swift
> +        )) { (result: Result<FoundIngredients, Error>) in
выдает ошибку: Generic parameter 'T' could not be inferred

2023-04-13 13:57 UTC, SviRiDoFFtru approved these changes

2023-04-13 13:59 UTC, merged