Сделал root, tabBar, main координаторы
uevuu/-Kitchen-Buddy-IOS-app pull request #2
Opened 2023-04-18 13:48 UTC by uevuu

сделал все про что говорили: rootCoordinator, mainCoordinator, tabBarCoordinator, main builder, service locator кроме замыкания для завершения координатора

2023-04-19 00:06 UTC, SviRiDoFFtru requested changes

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/ServiceLocator.swift
> +    var container: Container { get set }
наружу container не должен торчать, наружу мы только Resolver должны получать, и все

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/ServiceLocator.swift
> +    var container: Container
и соответственно container и assembler должны быть внутренними переменными (private)

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/Coordinator.swift
> +protocol Coordinator: AnyObject {
назови FlowCoordinatorProtocol (там намного понятней будет что это означает)

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/Coordinator.swift
> +    var childCoordinators: [Coordinator] { get set }
childCoordinators закрытая информация, ее должен знать каждый FlowCoordinator у себя внутри
соответственно этому не место в протоколе

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/Coordinator.swift
> +    var serviceLocator: ServiceLocator { get set }
и это не должно торчать наружу, это флоу координатор должен в init-е получать (а точнее resolver, а не целый ServiceLocator)

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/Coordinator.swift
> +    func finish()
у start и finish добавь параметр animated: Bool, чтобы была возможность выбирать как открывать тот или иной флоу координатор

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/Coordinator.swift
> +        childCoordinators.removeAll()
прежде чем очищать массив, ты должен у каждого childCoordinator-а вызвать finish

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/Coordinator.swift
> +    func finish() {
выносить в extension finish() плохая идея, ведь у каждого координатора может отличаться логика закрытия, в зависимости от назначения

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/FavouriteCoordinator.swift
> +    init(_ tabBarController: UITabBarController, _ serviceLocator: ServiceLocator) {
ну да, как я говорил, целый ServiceLocator мы не должны пихать во все координаторы, сущность ServiceLocator должна быть только в AppDelegate/SceneDelegate, вместо этого нужно сюда и в другие координаторы передавать Resolver тип

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/FavouriteCoordinator.swift
> +        tabBarController.viewControllers?.append(favouriteNavigationController)
в init-е мы ничего такого не делаем, такие вещи надо делать в start

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/FavouriteCoordinator.swift
> +        tabBarController.viewControllers?.append(favouriteNavigationController)
в init-е мы просто сохраняем все переданные параметры в приватные переменные

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/FavouriteCoordinator.swift
> +        tabBarController.viewControllers?.append(favouriteNavigationController)
аналогично для остальных твоих флоу координаторов

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Builders/MainBuilder.swift
> +protocol MainBuilderProtocol {
для билдеров вообще не нужен интерфейс, если хочешь сделать общий протокол для всех билетеров, то можешь сделать вот такой универсальный:

```swift 
protocol ModuleBuilderProtocol {
    func build() -> UIViewController
}
```

2023-04-19 00:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Builders/MainBuilder.swift
> +    var serviceLocator: ServiceLocator
аналогично предыдущим комментариям ~~ServiceLocator~~ Resolver

2023-04-21 17:56 UTC, SviRiDoFFtru requested changes

2023-04-21 17:56 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/MainCoordinator.swift
> +protocol MainCoordinatorProtocol: FlowCoordinatorProtocol {
единственно что, не нужно доп протоколы делать, каждый координатор пусть удовлетворяет только протоколу FlowCoordinatorProtocol

2023-04-21 17:56 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/MainCoordinator.swift
>      func showRecipe()
эти все методы уже внутри пусть будут, родительскому координатору (кто открывает этот) знать об этих методах и не нужно особо

2023-04-21 17:56 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/FavouriteCoordinator.swift
> +    private var navigationController = UINavigationController()
создавай его в методе start

2023-04-21 17:56 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/FavouriteCoordinator.swift
> +    private var parentTabBarController: UITabBarController
parentViewController weak всегда должен быть, чтобы не было цикла ссылок

2023-04-21 17:56 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/FavouriteCoordinator.swift
> +    private var navigationController = UINavigationController()
и он тоже должен быть weak

2023-04-21 17:56 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/FavouriteCoordinator.swift
> +    private var parentTabBarController: UITabBarController
аналогично с другими координаторами

2023-04-28 00:53 UTC, SviRiDoFFtru requested changes

2023-04-28 00:53 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/MainCoordinator.swift
> +        navigationController.setViewControllers([viewController], animated: false)
вместо navigationController.setViewControllers ты можешь сразу создавать выше  UINavigationController(rootViewController: viewController)

2023-04-28 00:53 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/MainCoordinator.swift
> +        navigationController.setViewControllers([viewController], animated: false)
вот пример реализации:
<img width="695" alt="Снимок экрана 2023-04-28 в 03 48 45" src="https://user-images.githubusercontent.com/1655116/235028300-90899bc3-5800-4843-b536-5a7c2e800945.png">

2023-04-28 00:53 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/MainCoordinator.swift
> +        navigationController.setViewControllers([viewController], animated: false)
у таб бара есть метод appendViewController, используй его, а порядок добавления уже задает родительский координатор

2023-04-28 00:53 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/MainCoordinator.swift
> +        navigationController.setViewControllers([viewController], animated: false)
и вынеси весь код в start методе в отдельный метод, чтобы было красиво, как тут:
<img width="372" alt="Снимок экрана 2023-04-28 в 03 51 08" src="https://user-images.githubusercontent.com/1655116/235028746-7d03902f-4a54-405b-ad3f-06c1766ec612.png">

2023-04-28 00:53 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/MainCoordinator.swift
> +        navigationController.setViewControllers([viewController], animated: false)
сделай аналогично для остальных координаторов, и в остальном вроде все ок, потом как созвонимся, еще пару моментов расскажу как улучшить в других местах (с resolver-ом и т п)

2023-05-02 22:40 UTC, SviRiDoFFtru requested changes

2023-05-02 22:40 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainBuilder.swift
> +    private var coordinator: MainFlowCoordinator
как я говорил, прямой ссылки на координатор не должно быть у модуля и у билдера соответственно

2023-05-02 22:40 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainBuilder.swift
> +    private var coordinator: MainFlowCoordinator
~~private var coordinator: MainFlowCoordinator~~
private var moduleOutput: MainModuleOutput?

2023-05-02 22:40 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainBuilder.swift
> +            networkService: networkService ?? NetworkService(),
такого тоже не должно быть, если не смогли отрезолвить сервис, то лучше пусть падает, чем непредвиденное поведение происходит

2023-05-02 22:40 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainFlowCoordinator.swift
> +        let mainBuilder = MainBuilder(resolver, self)
MainBuilder(resolver, self) недостаточно понятно выглядит, лучше параметры внешние указывать, так удобней
параметры не указываем внешние обычно тогда, когда либо название метода подразумевает или содержит название первого параметра (напр. `func dismissToRootAndOpenTab(_ tab: Tab)`), либо в методах-сеттерах (напр. `func setCircleColor(_ color: UIColor)`)

2023-05-02 22:40 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/View/MainViewController.swift
> +        button.frame = CGRect(x: 60, y: 120, width: 200, height: 50)
frame же это временно пока? потом на констрейнтах (SnapKit) переделаешь?

2023-05-02 22:40 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainBuilder.swift
> +            networkService: networkService ?? NetworkService(),
вот такой extension можешь сделать, чтобы не force-unwrap-ить при каждом резолве, все будет сокрыто здесь: 
```swift
extension Resolver {

    func resolve<T>() -> T {
        return resolve(T.self)!
    }

    func resolve<T>(name: String?) -> T {
        return resolve(T.self, name: name)!
    }

    func resolve<T, Arg1>(argument: Arg1) -> T {
        return resolve(T.self, argument: argument)!
    }
}
```

2023-05-02 22:40 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Wines/WinesBuilder.swift
> +    init(_ resolver: Resolver, _ coordinator: WinesFlowCoordinator) {
аналогично:
~~init(_ resolver: Resolver, _ coordinator: WinesFlowCoordinator)~~
init(resolver: Resolver, moduleOutput: WinesModuleOutput?)

2023-05-02 22:40 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/WinesViewController.swift
> +//
а этот файл залетел не в ту папку как будто

2023-05-03 03:49 UTC, uevuu commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/View/MainViewController.swift
> +        button.frame = CGRect(x: 60, y: 120, width: 200, height: 50)
да

2023-05-05 02:06 UTC, SviRiDoFFtru requested changes

2023-05-05 02:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Wines/WinesViewModel.swift
> +extension WinesViewModel: WinesModuleOutput {
это зачем?) у тебя вообще тут почти циклическая логика получается, и сам класс удовлетворяет протоколу и в output шлет то же самое

2023-05-05 02:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainFlowCoordinator.swift
> +    var onFinish: (() -> Void)?
во-первых private, и передавай это в init-е, и назови лучше finishHandler, так понятней)

2023-05-05 02:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainFlowCoordinator.swift
> +        onFinish?()
это вызываться должно после завершения всех дочерних координаторов, и контроллеров

2023-05-05 02:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/RecipeInfo/RecipeInfoModuleOutput.swift
> +    func goToPreviousModule()
я бы лучше назвал viewDidPop

2023-05-05 02:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/RecipeInfo/RecipeFlowCoordinator.swift
> +        finish(animated: false)
самому себя закрывать не очень, лучше сказать наружу, что я хочу закрыться, а родительский координатор (тот который открыл этот) закроет этот

2023-05-05 02:06 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/RecipeInfo/RecipeFlowCoordinator.swift
> +        finish(animated: false)
используя RecipeFlowCoordinatorOutput

2023-05-12 16:38 UTC, SviRiDoFFtru requested changes

2023-05-12 16:38 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/FlowCoordinatorProtocol.swift
> +//        first(where: { $0 is T }) as? T
а что это не оставил?

2023-05-12 16:38 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/FlowCoordinatorProtocol.swift
> +            finishAll(animated: animated, completion: completion)
не увидел сразу, у тебя здесь будет бесконечная рекурсия и crash

2023-05-12 16:38 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Extensions/Resolver+Extensions.swift
> +        // swiftlint:disable:next force_unwrapping
можно без next сделать на 9 строчке выключить, а после extension включить обратно

2023-05-12 16:38 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/AllSelectionRecipes/AllSelectionRecipesFlowCoordinator.swift
> +        childCoordinators.finishAll(animated: animated, completion: completion)
в этом completion мы должны делать dismiss/pop если это нужно, но точно не использовать верхнеуровневый completion, ведь мы его уже добавили в массив

2023-05-12 21:54 UTC, uevuu commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/AllSelectionRecipes/AllSelectionRecipesFlowCoordinator.swift
> +        childCoordinators.finishAll(animated: animated, completion: completion)
то есть тут просто nil передать?

2023-05-12 22:06 UTC, uevuu commented on Kitchen Buddy/Kitchen Buddy/Coordinators/FlowCoordinatorProtocol.swift
> +            finishAll(animated: animated, completion: completion)
37 и 38 строчку кода просто заменить на вот это 
var arr = self.dropFirst()

2023-05-13 01:41 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/AllSelectionRecipes/AllSelectionRecipesFlowCoordinator.swift
> +        childCoordinators.finishAll(animated: animated, completion: completion)
да, если нечего закрывать, то nil

2023-05-13 01:42 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Coordinators/FlowCoordinatorProtocol.swift
> +            finishAll(animated: animated, completion: completion)
нет, надо finishAll вызывать у уже измененного массива

2023-05-14 22:41 UTC, SviRiDoFFtru approved these changes

2023-05-15 13:46 UTC, merged