Make main module
uevuu/-Kitchen-Buddy-IOS-app pull request #3
Opened 2023-05-18 22:47 UTC by uevuu

без хеширование в CoreData

2023-05-20 18:43 UTC, SviRiDoFFtru requested changes

2023-05-20 18:43 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/View/MainViewController.swift
> +            DispatchQueue.main.async {
тут лучше просто без completion сообщать viewDidLoadEvent для ViewModel, а уже сама ViewModel должна поидее требовать обновления View когда данные загрузились

2023-05-20 18:43 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainViewModel.swift
> +    private let wines = [
это пока временный хардкод?

2023-05-20 18:43 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainViewModel.swift
>      private let output: MainModuleOutput?
output должен быть weak

2023-05-20 18:43 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainViewModel.swift
> +        if let existingIndex = lastRecipes.firstIndex(where: { $0.id == recipe.id }) {
можно всю эту логику унести в отдельный сервис, который будет отвечать за историю просмотров

2023-05-21 18:29 UTC, uevuu commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainViewModel.swift
> +    private let wines = [
список сортов вин никак с апи не получить, они должны быть вшиты в приложение

2023-05-21 18:30 UTC, uevuu commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainViewModel.swift
> +    private let wines = [
ну либо же засунуть это в json и считывать уже его

2023-05-22 02:55 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainViewModel.swift
> +    private let wines = [
что-то статичное конечно лучше в json хранить, чтобы удобней было обновлять

2023-05-22 03:01 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/MainViewModel.swift
> +        lastRecipes = lastRecipesService.getRecipes()
это уже сохранять здесь не нужно, ты всегда можешь их из сервиса получить, когда это необходимо

2023-05-22 03:01 UTC, SviRiDoFFtru commented on Kitchen Buddy/Kitchen Buddy/Modules/Main/Main/View/MainViewController.swift
> +            DispatchQueue.main.async {
у тебя замыкание осталось, я имел ввиду наружу говорить просто viewModel.viewDidLoadEvent(), а уже сама ViewModel будет там кидать запрос и в completion запроса говорить view?.reloadData() например

2023-05-23 20:41 UTC, merged